USE [ChessAnalysis]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GamePhases](
	[PhaseID] [int] IDENTITY(1,1) NOT NULL,
	[Phase] [varchar](10) NULL,
	[ScoreWeight] [decimal](7, 6) NULL,
 CONSTRAINT [PK_GP_PhaseID] PRIMARY KEY CLUSTERED 
(
	[PhaseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
