USE [ChessAnalysis]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACPL_Ranges](
	[ACPL_Group] [int] IDENTITY(1,1) NOT NULL,
	[ACPL_Range] [varchar](10) NULL,
	[LBound] [decimal](5, 2) NULL,
	[UBound] [decimal](5, 2) NULL,
 CONSTRAINT [PK_AR_ACPLGroup] PRIMARY KEY CLUSTERED 
(
	[ACPL_Group] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
