USE [ChessAnalysis]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[CalculateEEHCandidatesPercentages] (@MoveID int, @MinCPDiff float, @MaxCPDiff float)
RETURNS decimal(6,4)

AS

BEGIN
	IF @MinCPDiff NOT IN (0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9) OR @MaxCPDiff NOT IN (0.09, 0.19, 0.29, 0.39, 0.49, 0.59, 0.69, 0.79, 0.89, 1.00)
	BEGIN
		RETURN NULL
	End

	DECLARE @eval float
	SET @eval = (SELECT CAST((CASE WHEN T1_Eval LIKE '#+%' THEN 100.00 WHEN T1_Eval LIKE '#-%' THEN -100.00 ELSE T1_Eval END) as float) FROM EEHMoves WHERE MoveID = @MoveID)

	DECLARE @candidatecount int
	DECLARE @ct int
	SET @candidatecount = (SELECT CandidateMoves FROM EEHMoves WHERE MoveID = @MoveID)

	IF @candidatecount = 0
	BEGIN
		RETURN NULL
	End

	SET @ct =
	(SELECT
		CASE WHEN abs(@eval - CAST((CASE WHEN T1_Eval LIKE '#+%' THEN 100.00 WHEN T1_Eval LIKE '#-%' THEN -100.00 ELSE T1_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T2_Eval LIKE '#+%' THEN 100.00 WHEN T2_Eval LIKE '#-%' THEN -100.00 ELSE T2_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T3_Eval LIKE '#+%' THEN 100.00 WHEN T3_Eval LIKE '#-%' THEN -100.00 ELSE T3_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T4_Eval LIKE '#+%' THEN 100.00 WHEN T4_Eval LIKE '#-%' THEN -100.00 ELSE T4_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T5_Eval LIKE '#+%' THEN 100.00 WHEN T5_Eval LIKE '#-%' THEN -100.00 ELSE T5_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T6_Eval LIKE '#+%' THEN 100.00 WHEN T6_Eval LIKE '#-%' THEN -100.00 ELSE T6_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T7_Eval LIKE '#+%' THEN 100.00 WHEN T7_Eval LIKE '#-%' THEN -100.00 ELSE T7_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T8_Eval LIKE '#+%' THEN 100.00 WHEN T8_Eval LIKE '#-%' THEN -100.00 ELSE T8_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T9_Eval LIKE '#+%' THEN 100.00 WHEN T9_Eval LIKE '#-%' THEN -100.00 ELSE T9_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T10_Eval LIKE '#+%' THEN 100.00 WHEN T10_Eval LIKE '#-%' THEN -100.00 ELSE T10_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T11_Eval LIKE '#+%' THEN 100.00 WHEN T11_Eval LIKE '#-%' THEN -100.00 ELSE T11_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T12_Eval LIKE '#+%' THEN 100.00 WHEN T12_Eval LIKE '#-%' THEN -100.00 ELSE T12_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T13_Eval LIKE '#+%' THEN 100.00 WHEN T13_Eval LIKE '#-%' THEN -100.00 ELSE T13_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T14_Eval LIKE '#+%' THEN 100.00 WHEN T14_Eval LIKE '#-%' THEN -100.00 ELSE T14_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T15_Eval LIKE '#+%' THEN 100.00 WHEN T15_Eval LIKE '#-%' THEN -100.00 ELSE T15_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T16_Eval LIKE '#+%' THEN 100.00 WHEN T16_Eval LIKE '#-%' THEN -100.00 ELSE T16_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T17_Eval LIKE '#+%' THEN 100.00 WHEN T17_Eval LIKE '#-%' THEN -100.00 ELSE T17_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T18_Eval LIKE '#+%' THEN 100.00 WHEN T18_Eval LIKE '#-%' THEN -100.00 ELSE T18_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T19_Eval LIKE '#+%' THEN 100.00 WHEN T19_Eval LIKE '#-%' THEN -100.00 ELSE T19_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T20_Eval LIKE '#+%' THEN 100.00 WHEN T20_Eval LIKE '#-%' THEN -100.00 ELSE T20_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T21_Eval LIKE '#+%' THEN 100.00 WHEN T21_Eval LIKE '#-%' THEN -100.00 ELSE T21_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T22_Eval LIKE '#+%' THEN 100.00 WHEN T22_Eval LIKE '#-%' THEN -100.00 ELSE T22_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T23_Eval LIKE '#+%' THEN 100.00 WHEN T23_Eval LIKE '#-%' THEN -100.00 ELSE T23_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T24_Eval LIKE '#+%' THEN 100.00 WHEN T24_Eval LIKE '#-%' THEN -100.00 ELSE T24_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T25_Eval LIKE '#+%' THEN 100.00 WHEN T25_Eval LIKE '#-%' THEN -100.00 ELSE T25_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T26_Eval LIKE '#+%' THEN 100.00 WHEN T26_Eval LIKE '#-%' THEN -100.00 ELSE T26_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T27_Eval LIKE '#+%' THEN 100.00 WHEN T27_Eval LIKE '#-%' THEN -100.00 ELSE T27_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T28_Eval LIKE '#+%' THEN 100.00 WHEN T28_Eval LIKE '#-%' THEN -100.00 ELSE T28_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T29_Eval LIKE '#+%' THEN 100.00 WHEN T29_Eval LIKE '#-%' THEN -100.00 ELSE T29_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T30_Eval LIKE '#+%' THEN 100.00 WHEN T30_Eval LIKE '#-%' THEN -100.00 ELSE T30_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T31_Eval LIKE '#+%' THEN 100.00 WHEN T31_Eval LIKE '#-%' THEN -100.00 ELSE T31_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END +
		CASE WHEN abs(@eval - CAST((CASE WHEN T32_Eval LIKE '#+%' THEN 100.00 WHEN T32_Eval LIKE '#-%' THEN -100.00 ELSE T32_Eval END) as float)) BETWEEN @MinCPDiff AND @MaxCPDiff THEN 1 ELSE 0 END

		FROM EEHMoves

		WHERE MoveID = @MoveID
	)

	DECLARE @pcnt decimal(6,4)
	SET @pcnt = ROUND(@ct*1.00/@candidatecount,4)

	RETURN @pcnt
End
GO
