USE [ChessAnalysis]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TimeControlTypes](
	[TimeControlRank] [tinyint] IDENTITY(1,1) NOT NULL,
	[TimeControlType] [varchar](20) NOT NULL,
	[MinSeconds] [int] NULL,
	[MaxSeconds] [int] NULL,
 CONSTRAINT [PK_TCT_TimeControlRank] PRIMARY KEY CLUSTERED 
(
	[TimeControlRank] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [CK_TCT_TimeControlType] UNIQUE NONCLUSTERED 
(
	[TimeControlType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
