USE [ChessWarehouse]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dim].[Players](
	[PlayerID] [int] IDENTITY(1,1) NOT NULL,
	[SourceID] [tinyint] NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[FirstName] [varchar](30) NULL,
	[SelfFlag] [bit] NOT NULL,
 CONSTRAINT [PK_Players] PRIMARY KEY CLUSTERED 
(
	[PlayerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_Name] UNIQUE NONCLUSTERED 
(
	[SourceID] ASC,
	[LastName] ASC,
	[FirstName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dim].[Players] ADD  CONSTRAINT [DF_Players_SelfFlag]  DEFAULT ((0)) FOR [SelfFlag]
GO
ALTER TABLE [dim].[Players]  WITH CHECK ADD  CONSTRAINT [FK_Players_SourceID] FOREIGN KEY([SourceID])
REFERENCES [dim].[Sources] ([SourceID])
GO
ALTER TABLE [dim].[Players] CHECK CONSTRAINT [FK_Players_SourceID]
GO
