USE [ChessWarehouse]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dim].[Scores](
	[ScoreID] [tinyint] IDENTITY(1,1) NOT NULL,
	[ScoreName] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ScoreDesc] [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ScoreActive] [bit] NOT NULL,
	[ScoreProc]  AS ('UpdateMoveScores_ScoreID_'+CONVERT([nvarchar](30),[ScoreID])) PERSISTED,
 CONSTRAINT [PK_Scores] PRIMARY KEY CLUSTERED 
(
	[ScoreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UC_Scores_ScoreName] UNIQUE NONCLUSTERED 
(
	[ScoreName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dim].[Scores] ADD  CONSTRAINT [DF_Scores_ScoreActive]  DEFAULT ((0)) FOR [ScoreActive]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [dim].[trg_Scores] ON [dim].[Scores]

AFTER INSERT, DELETE

AS

BEGIN

	EXEC dbo.CreateScoreViews

END
GO
ALTER TABLE [dim].[Scores] ENABLE TRIGGER [trg_Scores]
GO
