USE [ChessWarehouse]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [stage].[BulkInsertGameData](
	[RecordKey] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Field1] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field2] [varchar](26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field3] [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field4] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field5] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field6] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field7] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field8] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field9] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field10] [varchar](92) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field11] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field12] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field13] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field14] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field15] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field16] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field17] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field18] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field19] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field20] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field21] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field22] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field23] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field24] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field25] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field26] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field27] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field28] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field29] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field30] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field31] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field32] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field33] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field34] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field35] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field36] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field37] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field38] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field39] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field40] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field41] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field42] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field43] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field44] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field45] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field46] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field47] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field48] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field49] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field50] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field51] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field52] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field53] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field54] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field55] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field56] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field57] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field58] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field59] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field60] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field61] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field62] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field63] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field64] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field65] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field66] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field67] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field68] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field69] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field70] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field71] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field72] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field73] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field74] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field75] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field76] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field77] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field78] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Field79] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [stage].[BulkInsertGameData]  WITH NOCHECK ADD  CONSTRAINT [FK_BulkInsertGameData_RecordKey] FOREIGN KEY([RecordKey])
REFERENCES [doc].[Records] ([RecordKey])
GO
ALTER TABLE [stage].[BulkInsertGameData] CHECK CONSTRAINT [FK_BulkInsertGameData_RecordKey]
GO
